-- Generated from generator/demo_specs/aws-thailand-automotive-assembly-twin.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-thailand-automotive-assembly-twin
-- This is the schema that is actually deployed for THAILAND_AUTOMOTIVE_ASSEMBLY_TWIN.

-- Alerts fire on the bottom tail of Assembly Line OEE
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_ASSEMBLY_LINE_OEE) AS T
  FROM RAW.EQUIPMENT_TELEMETRY
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_ASSEMBLY_LINE_OEE <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_ASSEMBLY_LINE_OEE), 2) AS AVG_ASSEMBLY_LINE_OEE,
  ROUND(AVG(f.KPI_DIGITAL_TWIN_SYNC), 2) AS AVG_DIGITAL_TWIN_SYNC,
  ROUND(AVG(f.KPI_QUALITY_DEFECTS_TODAY), 2) AS AVG_QUALITY_DEFECTS_TODAY,
  ROUND(AVG(f.KPI_CYCLE_TIME_VARIANCE), 2) AS AVG_CYCLE_TIME_VARIANCE,
  ROUND(AVG(f.KPI_ENERGY_PER_UNIT), 2) AS AVG_ENERGY_PER_UNIT,
  ROUND(AVG(f.KPI_SIMULATION_ACCURACY), 2) AS AVG_SIMULATION_ACCURACY
FROM RAW.EQUIPMENT_TELEMETRY f
JOIN RAW.ASSEMBLY_LINES e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_ASSEMBLY_LINE_OEE), 2) AS AVG_ASSEMBLY_LINE_OEE,
  ROUND(AVG(f.KPI_DIGITAL_TWIN_SYNC), 2) AS AVG_DIGITAL_TWIN_SYNC,
  ROUND(AVG(f.KPI_QUALITY_DEFECTS_TODAY), 2) AS AVG_QUALITY_DEFECTS_TODAY,
  ROUND(AVG(f.KPI_CYCLE_TIME_VARIANCE), 2) AS AVG_CYCLE_TIME_VARIANCE,
  ROUND(AVG(f.KPI_ENERGY_PER_UNIT), 2) AS AVG_ENERGY_PER_UNIT,
  ROUND(AVG(f.KPI_SIMULATION_ACCURACY), 2) AS AVG_SIMULATION_ACCURACY
FROM RAW.EQUIPMENT_TELEMETRY f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_ASSEMBLY_LINE_OEE) AS KPI_ASSEMBLY_LINE_OEE, AVG(KPI_DIGITAL_TWIN_SYNC) AS KPI_DIGITAL_TWIN_SYNC, AVG(KPI_QUALITY_DEFECTS_TODAY) AS KPI_QUALITY_DEFECTS_TODAY, AVG(KPI_CYCLE_TIME_VARIANCE) AS KPI_CYCLE_TIME_VARIANCE, AVG(KPI_ENERGY_PER_UNIT) AS KPI_ENERGY_PER_UNIT, AVG(KPI_SIMULATION_ACCURACY) AS KPI_SIMULATION_ACCURACY FROM RAW.EQUIPMENT_TELEMETRY),
     en AS (SELECT SUM(KPI_UNITS_PRODUCED_MTD) AS KPI_UNITS_PRODUCED_MTD FROM RAW.ASSEMBLY_LINES)
  SELECT 1 AS SORT_ORDER, 'Assembly Line OEE' AS TITLE, KPI_ASSEMBLY_LINE_OEE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ASSEMBLY_LINE_OEE), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Digital Twin Sync' AS TITLE, KPI_DIGITAL_TWIN_SYNC AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_DIGITAL_TWIN_SYNC), 1) AS DECIMAL(38,1))) || 's' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Quality Defects (Today)' AS TITLE, KPI_QUALITY_DEFECTS_TODAY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_QUALITY_DEFECTS_TODAY)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Units Produced (MTD)' AS TITLE, KPI_UNITS_PRODUCED_MTD AS VALUE_NUM, LTRIM(TO_VARCHAR(CAST(ROUND((KPI_UNITS_PRODUCED_MTD)) AS DECIMAL(38,0)), '999,999,999,999')) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Cycle Time Variance' AS TITLE, KPI_CYCLE_TIME_VARIANCE AS VALUE_NUM, '±' || TO_VARCHAR(CAST(ROUND((KPI_CYCLE_TIME_VARIANCE), 1) AS DECIMAL(38,1))) || 's' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Energy per Unit' AS TITLE, KPI_ENERGY_PER_UNIT AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ENERGY_PER_UNIT)) AS DECIMAL(38,0))) || ' ' || 'kWh' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Simulation Accuracy' AS TITLE, KPI_SIMULATION_ACCURACY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SIMULATION_ACCURACY), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
