-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Assembly Line Digital Twin
-- ============================================================================
USE DATABASE ASSEMBLY_TWIN;
USE SCHEMA ML;

-- ML.FORECAST: DOWNTIME_FORECAST_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.DOWNTIME_FORECAST_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.DOWNTIME_COST'),
  SERIES_COLNAME => 'LINE_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.DOWNTIME_FORECAST_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.DOWNTIME_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: VIBRATION_ANOMALY_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.VIBRATION_ANOMALY_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.VIBRATION_TIMESERIES'),
  SERIES_COLNAME => 'STATION_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.VIBRATION_ANOMALY_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.VIBRATION_ANOMALY_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.VIBRATION_TIMESERIES'), SERIES_COLNAME => 'STATION_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

