-- ============================================================================
-- 99_RESET.SQL — Reset Assembly Line Digital Twin to clean demo state
-- ============================================================================
USE DATABASE ASSEMBLY_TWIN;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_RETRAIN_MODELS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_HEALTH_SCORES SUSPEND;
ALTER TASK IF EXISTS APP.TASK_SYNC_TWINMAKER SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.LINE_OEE_REALTIME REFRESH;
ALTER DYNAMIC TABLE CURATED.EQUIPMENT_HEALTH_SCORE REFRESH;
ALTER DYNAMIC TABLE CURATED.DOWNTIME_COST REFRESH;
ALTER DYNAMIC TABLE CURATED.VIBRATION_TIMESERIES REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM ASSEMBLY_TWIN.RAW.EQUIPMENT_TELEMETRY → 750000
-- SELECT COUNT(*) FROM ASSEMBLY_TWIN.RAW.PRODUCTION_EVENTS → 45000
-- SELECT COUNT(*) FROM ASSEMBLY_TWIN.CURATED.LINE_OEE_REALTIME WHERE OEE < 0.65 → 2

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_SYNC_TWINMAKER RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_HEALTH_SCORES RESUME;
ALTER TASK IF EXISTS APP.TASK_RETRAIN_MODELS RESUME;
